//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TastefullySimple.IntegrationTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PageUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageUrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TastefullySimple.IntegrationTests.Resources.PageUrls", typeof(PageUrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/shop-our-products/collections/30-meal-kit-101142.
        /// </summary>
        internal static string _30MealKitFallDetailedPage {
            get {
                return ResourceManager.GetString("_30MealKitFallDetailedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/about-us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bbb.org/en/us/local-bbb/bbb-of-minnesota-and-north-dakota.
        /// </summary>
        internal static string BbbExternLlink {
            get {
                return ResourceManager.GetString("BbbExternLlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://myhq.tastefullysimple.com/myhq/LoginConsultant.aspx.
        /// </summary>
        internal static string ConsultantLoginExternalLink {
            get {
                return ResourceManager.GetString("ConsultantLoginExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/consultant-reactivation.
        /// </summary>
        internal static string ConsultantReactivation {
            get {
                return ResourceManager.GetString("ConsultantReactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/consultant-spotlight.
        /// </summary>
        internal static string ConsultantSpotlight {
            get {
                return ResourceManager.GetString("ConsultantSpotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/contact-us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/dsa-code-of-ethics.
        /// </summary>
        internal static string DsaCodeOfEthics {
            get {
                return ResourceManager.GetString("DsaCodeOfEthics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dsa.org/.
        /// </summary>
        internal static string DsaExternalLink {
            get {
                return ResourceManager.GetString("DsaExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://viewer.zmags.com/publication/70003167#/70003167/1.
        /// </summary>
        internal static string ECatalogExternalLink {
            get {
                return ResourceManager.GetString("ECatalogExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/employment.
        /// </summary>
        internal static string Employment {
            get {
                return ResourceManager.GetString("Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/tastefullysimple/?ref=nf.
        /// </summary>
        internal static string FacebookExternalLink {
            get {
                return ResourceManager.GetString("FacebookExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/consultant/find-a-consultant.
        /// </summary>
        internal static string FindConsultant {
            get {
                return ResourceManager.GetString("FindConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/guarantee.
        /// </summary>
        internal static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/tastefullysimpl/#.
        /// </summary>
        internal static string InstagramExternalLink {
            get {
                return ResourceManager.GetString("InstagramExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/meal-kits/meal-kit-delivery-service.
        /// </summary>
        internal static string MealKitDeliveryService {
            get {
                return ResourceManager.GetString("MealKitDeliveryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/our-products.
        /// </summary>
        internal static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.pinterest.com/tastefullysimpl/.
        /// </summary>
        internal static string PinterestExternalLink {
            get {
                return ResourceManager.GetString("PinterestExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/privacy-policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/shipping.
        /// </summary>
        internal static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/special-offers.
        /// </summary>
        internal static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/terms-of-use.
        /// </summary>
        internal static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/shop-our-products/30-meal-kits.
        /// </summary>
        internal static string Tso30MealKitsPage {
            get {
                return ResourceManager.GetString("Tso30MealKitsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tastefullysimple.com/.
        /// </summary>
        internal static string TsoHomePage {
            get {
                return ResourceManager.GetString("TsoHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/tastefullysimpl.
        /// </summary>
        internal static string TwitterExternalLink {
            get {
                return ResourceManager.GetString("TwitterExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/user/TastefullySimpleInc.
        /// </summary>
        internal static string YouTubeExternalLink {
            get {
                return ResourceManager.GetString("YouTubeExternalLink", resourceCulture);
            }
        }
    }
}
