//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TastefullySimple.IntegrationTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Selectors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Selectors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TastefullySimple.IntegrationTests.Resources.Selectors", typeof(Selectors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .breadcrumbs.hiddenOnMobile ol.
        /// </summary>
        internal static string Breadcrumbs {
            get {
                return ResourceManager.GetString("Breadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(1) li:nth-child(1) a.
        /// </summary>
        internal static string FooterAboutusLink {
            get {
                return ResourceManager.GetString("FooterAboutusLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks div:nth-child(2) ul li:nth-child(1) a.
        /// </summary>
        internal static string FooterBbbLink {
            get {
                return ResourceManager.GetString("FooterBbbLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks &gt;div:nth-child(1) div.
        /// </summary>
        internal static string FooterConnectWithUsTitle {
            get {
                return ResourceManager.GetString("FooterConnectWithUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(3) li:nth-child(2) a.
        /// </summary>
        internal static string FooterConsultantAgreementPdfLink {
            get {
                return ResourceManager.GetString("FooterConsultantAgreementPdfLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(3) li:nth-child(1) a.
        /// </summary>
        internal static string FooterConsultantLoginLink {
            get {
                return ResourceManager.GetString("FooterConsultantLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(3) li:nth-child(3) a.
        /// </summary>
        internal static string FooterConsultantReactivationLink {
            get {
                return ResourceManager.GetString("FooterConsultantReactivationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(3) li:nth-child(4) a.
        /// </summary>
        internal static string FooterConsultantSpotlightLink {
            get {
                return ResourceManager.GetString("FooterConsultantSpotlightLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(1) li:nth-child(3) a.
        /// </summary>
        internal static string FooterContactUsLink {
            get {
                return ResourceManager.GetString("FooterContactUsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(3) li:nth-child(5) a.
        /// </summary>
        internal static string FooterDsaCodeOfEthicslink {
            get {
                return ResourceManager.GetString("FooterDsaCodeOfEthicslink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks div:nth-child(2) ul li:nth-child(2) a.
        /// </summary>
        internal static string FooterDsaLink {
            get {
                return ResourceManager.GetString("FooterDsaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(2) li:nth-child(2) a.
        /// </summary>
        internal static string FooterECatalogFallWinter {
            get {
                return ResourceManager.GetString("FooterECatalogFallWinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(1) li:nth-child(4) a.
        /// </summary>
        internal static string FooterEmploymentLink {
            get {
                return ResourceManager.GetString("FooterEmploymentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks div:nth-child(1) ul li:nth-child(1) a.
        /// </summary>
        internal static string FooterFacebookLink {
            get {
                return ResourceManager.GetString("FooterFacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(2) li:nth-child(1) a.
        /// </summary>
        internal static string FooterFindConsultantLink {
            get {
                return ResourceManager.GetString("FooterFindConsultantLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(1) li:nth-child(2) a.
        /// </summary>
        internal static string FooterGuaranteeLink {
            get {
                return ResourceManager.GetString("FooterGuaranteeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks div:nth-child(1) ul li:nth-child(5) a.
        /// </summary>
        internal static string FooterInstagramLink {
            get {
                return ResourceManager.GetString("FooterInstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(2) li:nth-child(5) a.
        /// </summary>
        internal static string FooterMealKitDeliveryService {
            get {
                return ResourceManager.GetString("FooterMealKitDeliveryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(2) li:nth-child(4) a.
        /// </summary>
        internal static string FooterOurProductsLink {
            get {
                return ResourceManager.GetString("FooterOurProductsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks div:nth-child(1) ul li:nth-child(2) a.
        /// </summary>
        internal static string FooterPinterestLink {
            get {
                return ResourceManager.GetString("FooterPinterestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(2) li:nth-child(6) a.
        /// </summary>
        internal static string FooterPrivacyPolicyLink {
            get {
                return ResourceManager.GetString("FooterPrivacyPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks &gt;div:nth-child(2) div.
        /// </summary>
        internal static string FooterProudMemberTitle {
            get {
                return ResourceManager.GetString("FooterProudMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footer.
        /// </summary>
        internal static string FooterSelector {
            get {
                return ResourceManager.GetString("FooterSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(1) li:nth-child(5) a.
        /// </summary>
        internal static string FooterShippingAndDeliveryLink {
            get {
                return ResourceManager.GetString("FooterShippingAndDeliveryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(2) li:nth-child(3) a.
        /// </summary>
        internal static string FooterSpecialOffersLink {
            get {
                return ResourceManager.GetString("FooterSpecialOffersLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .footerLinks ul:nth-child(1) li:nth-child(6) a.
        /// </summary>
        internal static string FooterTermsOfUseLink {
            get {
                return ResourceManager.GetString("FooterTermsOfUseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks div:nth-child(1) ul li:nth-child(3) a.
        /// </summary>
        internal static string FooterTwitterLink {
            get {
                return ResourceManager.GetString("FooterTwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.externalLinks div:nth-child(1) ul li:nth-child(4) a.
        /// </summary>
        internal static string FooterYouTubeLink {
            get {
                return ResourceManager.GetString("FooterYouTubeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cartItems-price.
        /// </summary>
        internal static string HeaderCartItemsPrice {
            get {
                return ResourceManager.GetString("HeaderCartItemsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accountLinks li:nth-child(1) a:nth-child(2).
        /// </summary>
        internal static string HeaderCreateAccountLink {
            get {
                return ResourceManager.GetString("HeaderCreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #NoConsultant.
        /// </summary>
        internal static string HeaderFindConsultantButton {
            get {
                return ResourceManager.GetString("HeaderFindConsultantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .quickLinks li:nth-child(3) a.
        /// </summary>
        internal static string HeaderFindHostOrPartyButton {
            get {
                return ResourceManager.GetString("HeaderFindHostOrPartyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EmailAddress.
        /// </summary>
        internal static string HeaderModalEmailField {
            get {
                return ResourceManager.GetString("HeaderModalEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Password.
        /// </summary>
        internal static string HeaderModalPasswordField {
            get {
                return ResourceManager.GetString("HeaderModalPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #modal-submit.
        /// </summary>
        internal static string HeaderModalSignInButton {
            get {
                return ResourceManager.GetString("HeaderModalSignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accountLinks li:nth-child(1) a.myAccountDropdown-trigger.
        /// </summary>
        internal static string HeaderMyAccountDropdownTrigger {
            get {
                return ResourceManager.GetString("HeaderMyAccountDropdownTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .js-accountLinksName.
        /// </summary>
        internal static string HeaderMyAccountLinkName {
            get {
                return ResourceManager.GetString("HeaderMyAccountLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mainNav li:nth-child(7) a.
        /// </summary>
        internal static string HeaderNavBlogButton {
            get {
                return ResourceManager.GetString("HeaderNavBlogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mainNav li:nth-child(6) a.
        /// </summary>
        internal static string HeaderNavEntertainingButton {
            get {
                return ResourceManager.GetString("HeaderNavEntertainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mainNav li:nth-child(4) a.
        /// </summary>
        internal static string HeaderNavJoinUsButton {
            get {
                return ResourceManager.GetString("HeaderNavJoinUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mainNav li:nth-child(3) a.
        /// </summary>
        internal static string HeaderNavMealKitsButton {
            get {
                return ResourceManager.GetString("HeaderNavMealKitsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mainNav li:nth-child(5) a.
        /// </summary>
        internal static string HeaderNavPartyButton {
            get {
                return ResourceManager.GetString("HeaderNavPartyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mainNav li:nth-child(2) a.
        /// </summary>
        internal static string HeaderNavRecipesButton {
            get {
                return ResourceManager.GetString("HeaderNavRecipesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mainNav li:nth-child(1) a.
        /// </summary>
        internal static string HeaderNavShopButton {
            get {
                return ResourceManager.GetString("HeaderNavShopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accountLinks &gt; div &gt; ul &gt; li:nth-child(2) &gt; div &gt; a:nth-child(1).
        /// </summary>
        internal static string HeaderRecipeBoxLink {
            get {
                return ResourceManager.GetString("HeaderRecipeBoxLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accountLinks li:nth-child(2) a.myAccountDropdown-trigger.
        /// </summary>
        internal static string HeaderRecipesDropdownTrigger {
            get {
                return ResourceManager.GetString("HeaderRecipesDropdownTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #js-header.
        /// </summary>
        internal static string HeaderSelector {
            get {
                return ResourceManager.GetString("HeaderSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #mainSearch.
        /// </summary>
        internal static string HeaderShearchField {
            get {
                return ResourceManager.GetString("HeaderShearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .siteSearch-submit.
        /// </summary>
        internal static string HeaderShearchSubmitButton {
            get {
                return ResourceManager.GetString("HeaderShearchSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cartItems.
        /// </summary>
        internal static string HeaderShoppingCartButton {
            get {
                return ResourceManager.GetString("HeaderShoppingCartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cartItems-quantity.
        /// </summary>
        internal static string HeaderShoppingCartItemsQuantity {
            get {
                return ResourceManager.GetString("HeaderShoppingCartItemsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accountLinks li:nth-child(1) a:nth-child(1).
        /// </summary>
        internal static string HeaderSignInLink {
            get {
                return ResourceManager.GetString("HeaderSignInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .logo.
        /// </summary>
        internal static string HeaderTsoLogo {
            get {
                return ResourceManager.GetString("HeaderTsoLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accountLinks li:nth-child(3) a.myAccountDropdown-trigger.
        /// </summary>
        internal static string HeaderWishlistDropdownTrigger {
            get {
                return ResourceManager.GetString("HeaderWishlistDropdownTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .accountLinks &gt; div &gt; ul &gt; li:nth-child(3) &gt; div &gt; a:nth-child(1).
        /// </summary>
        internal static string HeaderWishListLink {
            get {
                return ResourceManager.GetString("HeaderWishListLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .notification-content.
        /// </summary>
        internal static string NotificationMessageProductTitle {
            get {
                return ResourceManager.GetString("NotificationMessageProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .notification-title.
        /// </summary>
        internal static string NotificationMessageTitle {
            get {
                return ResourceManager.GetString("NotificationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30-mealkits.
        /// </summary>
        internal static string ShopPageNavMenu30MealKits {
            get {
                return ResourceManager.GetString("ShopPageNavMenu30MealKits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .btn-add-cart.
        /// </summary>
        internal static string ShopPageProductAddToCartButton {
            get {
                return ResourceManager.GetString("ShopPageProductAddToCartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .btn-view-detail.
        /// </summary>
        internal static string ShopPageProductViewDetailsButton {
            get {
                return ResourceManager.GetString("ShopPageProductViewDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchFilters-selected.
        /// </summary>
        internal static string ShopPageSearchFiltersSelected {
            get {
                return ResourceManager.GetString("ShopPageSearchFiltersSelected", resourceCulture);
            }
        }
    }
}
